# Generated by Django 3.0.8 on 2020-07-26 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200726_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='relation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 8, 0, 4, 174358)),
        ),
    ]
