# Generated by Django 3.0.8 on 2020-08-02 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200803_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='relation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 4, 56, 8, 271161)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 4, 56, 8, 272156)),
        ),
    ]
