# Generated by Django 3.0.8 on 2020-07-26 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200726_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 2, 7, 21, 659308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
