# Generated by Django 3.0.8 on 2020-08-02 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200726_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 23, 22, 58, 813643, tzinfo=utc)),
        ),
    ]
